CREATE TABLE IF NOT EXISTS "requests" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Requestor" TEXT,
    "SubmitDate" INTEGER,
    "QuoteNum" TEXT,
    "VendName" TEXT,
    "VendAdd" TEXT,
    "VendCity" TEXT,
    "VendState" TEXT,
    "VendZip" TEXT,
    "VendPhnNum" TEXT,
    "VendFaxNum" TEXT,
    "VendContact" TEXT,
    "VendEmail" TEXT,
    "VendWebSite" TEXT,
    "Billable" TEXT,
    "Customer_Name" TEXT,
    "Project_Name" TEXT,
    "Account_Number" TEXT,
    "Delivery_Date" INTEGER,
    "Deliver_To" TEXT,
    "Delivery_Address" TEXT,
    "Delivery_City" TEXT,
    "Delivery_Zip" TEXT,
    "DeliveryPhnNum" TEXT,
);
